language: scala
sudo: false
jdk:
  - oraclejdk8
  - openjdk11
script:
- sbt test "^ scripted"
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
